apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: guardian-v2-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
